# Use the official Python image from the Docker Hub
FROM python:3.5-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the necessary packages
RUN pip install kafka-python

# Run the Kafka producer script
CMD ["python", "create_topic_send_data.py"]
